version: '3.3'
services:
  mysqlservice:
    image: mysql:5.5
    ports:
      - 3306:3306
    container_name: mysql-container
    network_mode: host
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  productService:
    image: products
    build: ./UserProductService
    restart: always
    hostname: localhost
    network_mode: host
    depends_on:
      - mongodb
    ports:
      - 8089:8089
  mongodb:
    image: mongo:3.2-jessie
    ports:
      - 27017:27017
    container_name: mongo
    network_mode: host

  authenticationservice:
    container_name: user-authentication-service
    build: UserAuthenticationService/
    hostname: localhost
    network_mode: host
    ports:
      - 8082:8082
    depends_on:
      - mysqlservice
    restart: always
